import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

// 단일 꿈 PDF
export async function exportDreamPdf(dream: any) {
  const el = document.createElement('div')
  el.style.width = '794px'
  el.style.padding = '60px'
  el.style.backgroundColor = '#070712'
  el.style.color = 'white'
  el.style.fontFamily = 'sans-serif'
  el.style.position = 'fixed'
  el.style.top = '-9999px'
  el.style.left = '-9999px'

  const emotions = dream.emotions ?? []
  const scores = dream.emotion_scores ?? {}
  const sorted = [...emotions].sort((a: string, b: string) => (scores[b] ?? 0) - (scores[a] ?? 0))

  el.innerHTML = `
    <div style="background: linear-gradient(135deg, #1a0a2e, #0f0520); padding: 30px; border-radius: 12px; margin-bottom: 30px;">
      <div style="color: #a78bfa; font-size: 12px; letter-spacing: 4px; margin-bottom: 8px;">DREAMSYNC</div>
      <div style="font-size: 24px; font-weight: 900; margin-bottom: 6px;">Dream Journal</div>
      <div style="color: #6b7280; font-size: 13px;">${new Date(dream.created_at).toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      ${dream.main_tag ? `<div style="display: inline-block; margin-top: 10px; padding: 4px 14px; border-radius: 20px; border: 1px solid rgba(147,51,234,0.4); color: #c4b5fd; font-size: 13px;">✦ ${dream.main_tag}</div>` : ''}
    </div>

    <div style="margin-bottom: 24px;">
      <div style="color: #6b7280; font-size: 10px; letter-spacing: 3px; margin-bottom: 10px;">꿈 내용</div>
      <div style="color: #e2e8f0; font-size: 14px; line-height: 1.8;">${dream.content}</div>
    </div>

    ${dream.interpretation && !dream.interpretation.includes('플랜을 업그레이드') ? `
    <div style="background: rgba(124,58,237,0.1); border: 1px solid rgba(124,58,237,0.3); border-radius: 12px; padding: 20px; margin-bottom: 24px;">
      <div style="color: #a78bfa; font-size: 10px; letter-spacing: 3px; margin-bottom: 10px;">🔮 AI 해석 (Jung 심리학)</div>
      <div style="color: #c4b5fd; font-size: 13px; line-height: 1.8; font-style: italic;">${dream.interpretation}</div>
    </div>` : ''}

    ${sorted.length > 0 ? `
    <div style="margin-bottom: 24px;">
      <div style="color: #6b7280; font-size: 10px; letter-spacing: 3px; margin-bottom: 14px;">감정</div>
      ${sorted.map((e: string, i: number) => `
        <div style="margin-bottom: 10px;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
            <span style="color: ${i === 0 ? '#e9d5ff' : '#c4b5fd'}; font-size: 13px; font-weight: ${i === 0 ? 'bold' : 'normal'};">${i === 0 ? '✦ ' : ''}${e}</span>
            <span style="color: #6b7280; font-size: 12px;">${scores[e] ? scores[e] + '%' : ''}</span>
          </div>
          <div style="background: rgba(255,255,255,0.06); border-radius: 4px; height: 6px;">
            <div style="background: #7c3aed; border-radius: 4px; height: 6px; width: ${scores[e] ? scores[e] + '%' : '50%'};"></div>
          </div>
        </div>
      `).join('')}
    </div>` : ''}

    ${(dream.keywords ?? []).length > 0 ? `
    <div>
      <div style="color: #6b7280; font-size: 10px; letter-spacing: 3px; margin-bottom: 10px;">핵심 상징</div>
      <div>${(dream.keywords as string[]).map((k: string) => `<span style="display: inline-block; margin: 3px; padding: 4px 12px; border-radius: 20px; border: 1px solid rgba(99,102,241,0.3); color: #a5b4fc; font-size: 12px;">#${k}</span>`).join('')}</div>
    </div>` : ''}

    <div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.06); color: #374151; font-size: 11px; text-align: center;">
      Generated by Dreamsync — AI Dream Synchronizer
    </div>
  `

  document.body.appendChild(el)

  const canvas = await html2canvas(el, { backgroundColor: '#070712', scale: 2 })
  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const imgH = (canvas.height * pageW) / canvas.width

  if (imgH <= pageH) {
    pdf.addImage(imgData, 'PNG', 0, 0, pageW, imgH)
  } else {
    let y = 0
    while (y < canvas.height) {
      const sliceH = Math.min((pageH * canvas.width) / pageW, canvas.height - y)
      const sliceCanvas = document.createElement('canvas')
      sliceCanvas.width = canvas.width
      sliceCanvas.height = sliceH
      const ctx = sliceCanvas.getContext('2d')!
      ctx.drawImage(canvas, 0, -y)
      pdf.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', 0, 0, pageW, (sliceH * pageW) / canvas.width)
      y += sliceH
      if (y < canvas.height) pdf.addPage()
    }
  }

  document.body.removeChild(el)
  pdf.save(`dreamsync-${new Date(dream.created_at).toISOString().slice(0, 10)}.pdf`)
}

// 이달 꿈 전체 PDF 북
export async function exportMonthlyPdf(dreams: any[]) {
  const now = new Date()
  const monthStr = now.toLocaleDateString('ko-KR', { year: 'numeric', month: 'long' })

  const el = document.createElement('div')
  el.style.width = '794px'
  el.style.backgroundColor = '#070712'
  el.style.color = 'white'
  el.style.fontFamily = 'sans-serif'
  el.style.position = 'fixed'
  el.style.top = '-9999px'
  el.style.left = '-9999px'

  const dreamsHtml = dreams.map((dream, index) => {
    const emotions = dream.emotions ?? []
    const scores = dream.emotion_scores ?? {}
    const sorted = [...emotions].sort((a: string, b: string) => (scores[b] ?? 0) - (scores[a] ?? 0))

    return `
      <div style="padding: 60px; min-height: 1123px; page-break-after: always; position: relative;">
        <div style="background: linear-gradient(135deg, #1a0a2e, #0f0520); padding: 24px; border-radius: 12px; margin-bottom: 28px; display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <div style="color: #6b7280; font-size: 12px; margin-bottom: 4px;">${new Date(dream.created_at).toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
            ${dream.main_tag ? `<div style="color: #c4b5fd; font-size: 16px; font-weight: bold;">✦ ${dream.main_tag}</div>` : ''}
          </div>
          <div style="color: #4b5563; font-size: 12px;">${index + 1} / ${dreams.length}</div>
        </div>

        <div style="margin-bottom: 24px;">
          <div style="color: #6b7280; font-size: 10px; letter-spacing: 3px; margin-bottom: 10px;">꿈 내용</div>
          <div style="color: #e2e8f0; font-size: 14px; line-height: 1.8;">${dream.content}</div>
        </div>

        ${dream.interpretation && !dream.interpretation.includes('플랜을 업그레이드') ? `
        <div style="background: rgba(124,58,237,0.1); border: 1px solid rgba(124,58,237,0.3); border-radius: 12px; padding: 20px; margin-bottom: 24px;">
          <div style="color: #a78bfa; font-size: 10px; letter-spacing: 3px; margin-bottom: 10px;">🔮 AI 해석</div>
          <div style="color: #c4b5fd; font-size: 13px; line-height: 1.8; font-style: italic;">${dream.interpretation}</div>
        </div>` : ''}

        ${sorted.length > 0 ? `
        <div style="margin-bottom: 24px;">
          <div style="color: #6b7280; font-size: 10px; letter-spacing: 3px; margin-bottom: 14px;">감정</div>
          ${sorted.map((e: string, i: number) => `
            <div style="margin-bottom: 10px;">
              <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
                <span style="color: ${i === 0 ? '#e9d5ff' : '#c4b5fd'}; font-size: 13px;">${i === 0 ? '✦ ' : ''}${e}</span>
                <span style="color: #6b7280; font-size: 12px;">${scores[e] ? scores[e] + '%' : ''}</span>
              </div>
              <div style="background: rgba(255,255,255,0.06); border-radius: 4px; height: 6px;">
                <div style="background: #7c3aed; border-radius: 4px; height: 6px; width: ${scores[e] ? scores[e] + '%' : '50%'};"></div>
              </div>
            </div>
          `).join('')}
        </div>` : ''}

        <div style="position: absolute; bottom: 30px; left: 60px; right: 60px; border-top: 1px solid rgba(255,255,255,0.06); padding-top: 12px; color: #374151; font-size: 10px; text-align: center;">
          Dreamsync Dream Book · ${monthStr}
        </div>
      </div>
    `
  }).join('')

  el.innerHTML = `
    <!-- 표지 -->
    <div style="padding: 60px; min-height: 1123px; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; background: linear-gradient(135deg, #070712, #1a0a2e); page-break-after: always;">
      <div style="color: #a78bfa; font-size: 14px; letter-spacing: 6px; margin-bottom: 24px;">DREAMSYNC</div>
      <div style="font-size: 48px; font-weight: 900; margin-bottom: 16px;">Dream Book</div>
      <div style="color: #7c3aed; font-size: 20px; margin-bottom: 12px;">${monthStr}</div>
      <div style="color: #4b5563; font-size: 14px;">총 ${dreams.length}개의 꿈</div>
    </div>
    ${dreamsHtml}
  `

  document.body.appendChild(el)

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const pages = el.children

  for (let i = 0; i < pages.length; i++) {
    if (i > 0) pdf.addPage()
    const canvas = await html2canvas(pages[i] as HTMLElement, {
      backgroundColor: '#070712',
      scale: 2,
      width: 794,
    })
    const imgData = canvas.toDataURL('image/png')
    pdf.addImage(imgData, 'PNG', 0, 0, pageW, pageH)
  }

  document.body.removeChild(el)
  pdf.save(`dreamsync-book-${now.toISOString().slice(0, 7)}.pdf`)
}
