import jsPDF from 'jspdf'

interface Dream {
  content: string
  interpretation: string
  emotions: string[]
  keywords: string[]
  emotion_scores: Record<string, number> | null
  main_tag: string | null
  created_at: string
  visibility: string
}

export async function exportDreamPdf(dream: Dream) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  // 배경색
  doc.setFillColor(7, 7, 18)
  doc.rect(0, 0, pageW, pageH, 'F')

  // 헤더 배경
  doc.setFillColor(30, 20, 60)
  doc.rect(0, 0, pageW, 45, 'F')

  // 로고
  doc.setTextColor(167, 139, 250)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('DREAMSYNC', margin, y + 8)

  // 날짜
  doc.setTextColor(100, 100, 130)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  const dateStr = new Date(dream.created_at).toLocaleDateString('ko-KR', {
    year: 'numeric', month: 'long', day: 'numeric'
  })
  doc.text(dateStr, pageW - margin, y + 8, { align: 'right' })

  // 타이틀
  doc.setTextColor(230, 230, 250)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Dream Journal', margin, y + 22)

  // main_tag
  if (dream.main_tag) {
    doc.setTextColor(167, 139, 250)
    doc.setFontSize(10)
    doc.text(`✦ ${dream.main_tag}`, margin, y + 32)
  }

  y = 55

  // 구분선
  doc.setDrawColor(50, 40, 80)
  doc.line(margin, y, pageW - margin, y)
  y += 10

  // 꿈 내용
  doc.setTextColor(150, 150, 170)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text('DREAM CONTENT', margin, y)
  y += 6

  doc.setTextColor(210, 210, 230)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const contentLines = doc.splitTextToSize(dream.content, contentW)
  doc.text(contentLines, margin, y)
  y += contentLines.length * 5 + 10

  // AI 해석
  if (dream.interpretation && !dream.interpretation.includes('플랜을 업그레이드')) {
    doc.setDrawColor(50, 40, 80)
    doc.line(margin, y, pageW - margin, y)
    y += 8

    doc.setTextColor(150, 150, 170)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text('AI INTERPRETATION (JUNGIAN PSYCHOLOGY)', margin, y)
    y += 6

    doc.setFillColor(20, 15, 40)
    const interpLines = doc.splitTextToSize(dream.interpretation, contentW - 10)
    doc.rect(margin, y - 3, contentW, interpLines.length * 5 + 8, 'F')

    doc.setTextColor(196, 181, 253)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'italic')
    doc.text(interpLines, margin + 5, y + 3)
    y += interpLines.length * 5 + 14
  }

  // 감정
  if (dream.emotions && dream.emotions.length > 0) {
    doc.setDrawColor(50, 40, 80)
    doc.line(margin, y, pageW - margin, y)
    y += 8

    doc.setTextColor(150, 150, 170)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text('EMOTIONS', margin, y)
    y += 6

    const scores = dream.emotion_scores ?? {}
    const sorted = [...dream.emotions].sort((a, b) => (scores[b] ?? 0) - (scores[a] ?? 0))

    sorted.forEach((e, i) => {
      const score = scores[e]
      const barW = contentW - 60
      const fillW = score ? (score / 100) * barW : barW * 0.5

      doc.setTextColor(196, 181, 253)
      doc.setFontSize(10)
      doc.setFont('helvetica', i === 0 ? 'bold' : 'normal')
      doc.text(e, margin, y)

      // 막대 배경
      doc.setFillColor(30, 20, 60)
      doc.roundedRect(margin + 40, y - 3.5, barW, 5, 1, 1, 'F')

      // 막대 채우기
      doc.setFillColor(124, 58, 237)
      doc.roundedRect(margin + 40, y - 3.5, fillW, 5, 1, 1, 'F')

      if (score) {
        doc.setTextColor(130, 120, 160)
        doc.setFontSize(8)
        doc.text(`${score}%`, pageW - margin, y, { align: 'right' })
      }

      y += 8
    })
    y += 4
  }

  // 핵심 상징
  if (dream.keywords && dream.keywords.length > 0) {
    doc.setDrawColor(50, 40, 80)
    doc.line(margin, y, pageW - margin, y)
    y += 8

    doc.setTextColor(150, 150, 170)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text('KEY SYMBOLS', margin, y)
    y += 6

    doc.setTextColor(165, 180, 252)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const kwText = dream.keywords.map(k => `#${k}`).join('  ')
    doc.text(kwText, margin, y)
    y += 10
  }

  // 푸터
  doc.setFillColor(20, 15, 40)
  doc.rect(0, pageH - 15, pageW, 15, 'F')
  doc.setTextColor(80, 70, 100)
  doc.setFontSize(8)
  doc.text('Generated by Dreamsync — AI Dream Synchronizer', pageW / 2, pageH - 6, { align: 'center' })

  // 다운로드
  const fileName = `dreamsync-${new Date(dream.created_at).toISOString().slice(0, 10)}.pdf`
  doc.save(fileName)
}
